### ISSUE TITLE
Consider non-standard time averaging approach

### ISSUE THREAD

**Issue by zross** [zross/sensorDataImport#22]
We discussed creating a sequence of times beginning at a set date/time and then using this to aggregate if we need, say, 15 minute intervals rather than just 1 minute, 1 hour and 24 hour.

**Comment by zross** [comment]
@dwjack what is the earliest possible date of any sensor file from any project? I'm creating the functions for "non-standard" time averaging intervals and, in order to make sure that there will be complete consistency between all projects, sensors etc, I'll start the interval creation from a certain time point but that time point needs to be able to include any start date/time and any interval chosen. Jan 1, 1970, though, would create a bigger file than necessary. What would you suggest?

**Comment by dwjack** [comment]
1 Jan 2007 is safe.

thanks
