### ISSUE TITLE
Do we need an "undo" button after uploads?

### ISSUE THREAD

**Issue by zross** [zross/sensorDataImport#23]
This would be pretty involved but could be useful.

**Comment by zross** [comment]
We have decided that this is required.

**Comment by zross** [comment]
@dwjack should this be in the Shiny app or an R function? It depends a little on who you anticipate working with the data. Implementing this in Shiny would take longer but would allow people unfamiliar with R to delete. But if you expect everyone working with this app to be familiar with R then we can just have an R function. Which do you want?

**Comment by dwjack** [comment]
I prefer the function (a little less likely to be used by mistake). Thanks!

**Comment by SteveChillrud** [comment]
That is fine with me too

Steven Chillrud

Lamont-Doherty Earth Observatory of Columbia Univ.
61 Rt 9W
Palisades, NY 10964
chilli@ldeo.columbia.edu
tel: 845-365-8893
fax: 845-365-8155

**Comment by zross** [comment]
Closing this issue -- I opened a new one #35
