### ISSUE TITLE
Remove session numbers and remove data for microPEM (MPM) files

### ISSUE THREAD

**Issue by zross** [zross/sensorDataImport#41]
Cara writes in this Google doc https://docs.google.com/document/d/1CWH4PMbcprurXvq4O1uALZxyNgPcnhQDXioffmp3QYE/edit?ts=589de312: 

We are also having problem with the session segmenting and it is cutting off data. If the participant forgot to turn the microPEM off and it ran for over 40 hours, the database would end the file prematurely. We could signify the end of a session based on if buttons are pressed, but there might still be problems with this (i.e they hit a button by accident while putting the monitor in the pocket). Since we can’t find a good way to catch these, then we might need to just take the session numbering out of the database script, and identify session on our own.

Proposed solution: For the microPEM data files (MPM), don’t have the upload function to the data base assign session numbers and remove data.  Just upload all the data in the file and we will deal with it outside of the database.  But we are open to other suggestions/ way to still have session numbers but prevent any data loss.

**Comment by zross** [comment]
When you say "don't have the upload function to the data base assign session numbers and remove data" -- what do you mean by remove data?

**Comment by caraMsmith** [comment]
So what we think is happening is that the database is automatically assigning session numbers and this is leading to data being removed if the participants did not turn off the monitor properly. If it runs for a long time, the data is removed because it thinks the session should have ended.

**Comment by zross** [comment]
@caraMsmith Do you have any data I can use for examples?

**Comment by caraMsmith** [comment]
@zross Here is an example : https://drive.google.com/open?id=0BwE-isc6rrunTzROc0JOVEhRT1U

**Comment by zross** [comment]
@caraMsmith I may need more clarification on how you are accessing the data etc to make sure I'm doing what you want on this one. The database does not discard any data. Are you using the `get_sensor_data` function? My guess is that this is what you're using and so it "seems" like data is missing but it's really not. Here is what happens when you upload:

1. The table is process, the header information is appended as new columns. 
2. For micro PEM there is a function to try to identify sessions. I put that below. Basically if there is a time gap between two rows of data of more than 12 hours this helps to split the data in to sessions. In addition, beyond the sessions, if the length of a session is less than 10 minutes we call this a "Non session". The results of these calculations are added to the `sessionid` field
3. Data is uploaded to the database. Every single line of data is uploaded regardless of session status. This includes non-sessions
4. So the database has all the data. But if you're extracting data from the database this is where it gets filtered by default (but you can tell it not to. The `get_sensor_data()` function has an argument called `clean_first` that defaults to TRUE. Right now, the only thing that this does is filters out the "Non sessions". So if you want all data you can simply run `get_sensor_data()` with `clean_first = FALSE`

Would this solve the issue or do you want me to do something else?

```r
find_gaps_assign_session <- function (datetime) {
  #datetime<-data$datetime
  datetime<-as.POSIXct(datetime)
  diff<-datetime[-length(datetime)]-datetime[-1]
  
  # which are long gaps (more than 12 hours)
  to<-c(which(as.numeric(diff)<(-12*60*60)), length(datetime))
  from<- c(1, to[-length(to)]+1)
  #to<-c(to, nrow(data))
  
  dat<-data.frame(from=from, to=to)
  dat$length<-(dat$to-dat$from)+1
  
  # you can subtract dates but the units might end up different
  dat$session_time<-difftime(datetime[dat$to], datetime[dat$from], units="secs")
  
  # if the length of a session is less than 10 minutes
  # we will consider this a non-session
  
  dat$tooshort <- dat$session_time < 10 * 60
  
  dat$session_id <- "Non session"
  
  
  dat$session_id[!dat$tooshort]<-addZero(1:sum(!dat$tooshort))
  
  session<-rep(dat$session_id, times=dat$length)
  
  if(length(session)!=length(datetime)) stop("There is a problem with the gap/assign session")
  
  return(session)
  
}
```

**Comment by caraMsmith** [comment]
That was likely the problem and it looks like that would solve this issue.
