### ISSUE TITLE
Change instrument ID to 10 characters

### ISSUE THREAD

**Issue by zross** [zross/sensorDataImport#42]
Cara writes https://docs.google.com/document/d/1CWH4PMbcprurXvq4O1uALZxyNgPcnhQDXioffmp3QYE/edit?ts=589de312

Repeated air monitor IDs

Problem our Air Monitor IDs are not unique: we did not think of good naming protocols for the monitor IDs. Specifically for the microAeths and microPEMs- we are not currently assigning enough numeric characters to the monitor IDs to be unique (we assigned two numbers but we should have assigned 4 since there are now over 1000 AE51 units out there in the world and if we have to replace any of them we will potentially have units that have the same last two numbers (e.g 104 and 1104 both end in 04 which is how we refer to them now).  Same thing with microPEMs 

Proposed solution is to go to 4 numeric characters (instead of 2) in the monitor ID name we use for writing file names for uploading to the database for the two air monitors. Ex: MPM#### , MAE#### instead of the current MPM## and MAE##

**Comment by zross** [comment]
If I'm understanding this it is not much work on my end. You're just asking that I expand the number of characters in the field to 7 or more right? So this field is called `instrumentid` and is listed at 6 digits, I can change this to 10 to accommodate your expansion. Is there anything else you would need from me on this one?

**Comment by caraMsmith** [comment]
Yes, changing it to 10 characters would be ideal. That's all for this issue, thanks!
