### ISSUE TITLE
Automatically plot data when uploaded

### ISSUE THREAD

**Issue by zross** [zross/sensorDataImport#43]
Cara writes: https://docs.google.com/document/d/1CWH4PMbcprurXvq4O1uALZxyNgPcnhQDXioffmp3QYE/edit?ts=589de312

 Automatic plotting data- would want relevant plots to pop up for each data file uploaded so that field team can assess how things are going, as well as pdfs of plots saved in systematic way (see below)
* Time-series of black carbon in ug/m^3 from microaeth;
* Time-series of PM2.5 in ug/m^3 from microPEM; 
* Time-serie of  plot time series of microPEM “Vector Sum Composite (activity)”  and Hexoskin “activity” data in 1 minute average data for both

One way to organize the output data plots/files from the database is to name systematically with SubjectID_SessionStartDate_monitorID_parameter (e.g., Bik004_07162015_and then put into folders (one each per subject ID)/subfolders (one each for Session Start Date). 

The plots need to be named with these information and have these in the title. 

Having a saved file would be helpful in addition to a shiny plot.

**Comment by zross** [comment]
From e-mail:

We were thinking of times series plots of the following for each session:
1.  Time-series: of black carbon (BC) from microaeth;
2. Time-series: of PM2.5 (RH-Corrected Nephelometer HR) from microPEM; 
3. Time-series of  plot time series of microPEM “Vector Sum Composite (activity)”  in 1 minute average data
4. Time-series of Hexoskin “activity” data in 1 minute average data 
5. Times series of ATN from microaeth
6. time series of minute ventilation (ve.ml) from Hexoskin data
7. time series of heart rate (HR) from Hexoskin data

**Comment by zross** [comment]
My presumption is that you don't want me to spend time on making pretty plots. I'm putting samples in the wiki for review. See here: https://github.com/zross/sensorDataImport/wiki/Plotting-examples. Questions that I'm going to pose via e-mail are:

1) These files often have many NA values, is it helpful to plot these? With NAs included it's hard to see the data, without you might miss issues, I'm not sure.

2) Are these plots what you had in mind?

3) Based on the conversation you want these in the shiny app AND saved to a directory correct? Note that making these plots takes a while because it's a lot of data, I'm not sure how many files you upload at once but this could be an issue.

4) If you want to save the plots, and I'm assuming you do, where do you want me to put them? I could allow you to select a place to save them but this would take some time to code -- probably this is best, but if you want it done quickly we could pick a permanent directory.

**Comment by caraMsmith** [comment]
1) Please remove the NAs ; those mainly occurs when the monitor is off as it still logs battery voltage in standby mode. 
2) Yes the ones with a panel for each session is what we had in mind
3) Yes, we want them saved as well. Will upload on person at a time so shouldn't be a problem
4) We would save the files to a folder on the computer

**Comment by SteveChillrud** [comment]
Zev, correct we don’t need pretty plots but we do need them also plotted by session as you have done.
It is not clear to me that you saw my email from yesterday since you never updated the list of plots for the changes I suggested below
Did you get it?  Do you understand the changes?

thanks
steve


> Begin forwarded message:
> 
> From: Steven Chillrud <chilli@ldeo.columbia.edu>
> Subject: Re: Example graphs?
> Date: April 27, 2017 at 3:48:45 PM EDT
> To: Zev Ross <zev@zevross.com>
> Cc: "Smith, Cara M." <cms2308@cumc.columbia.edu>, "Jack, Darby W." <dj2183@cumc.columbia.edu>, Qiang Yang <qyang@ldeo.columbia.edu>
> 
> Zev, the other addition is just to calculate the run time in hrs of each device- could go with each plot or in a summary file or both if easy.
> also something to let us know that the Strava app was used.
> 
> So to have the list in all one place and re-ordered for plots to go together with the device
> 
>  1.  Time-series of black carbon (BC) from microaeth with Run time for each session in hrs (run time printed either on the plot or in a separate summary file);
>  2.  Times series of ATN from microaeth
> 
>  3.  Time-series of PM2.5 (RH-Corrected Nephelometer HR) from microPEM with Run time printed for each session in hrs (run time printed either on the plot or in a separate summary file);
>  4.  Time-series of  plot time series of microPEM “Vector Sum Composite (activity)”  in 1 minute average data
> 
>  4.  Time-series of Hexoskin “activity” data in 1 minute average data ((run time printed either on the plot or in a separate summary file);
>  5.  Time series of minute ventilation (ve.ml <http://ve.ml/>) from Hexoskin data 
>  6.  time series of heart rate (HR) from Hexoskin data
> 
> 7.   Time series showing existence of data as a solid line (1 for existence of lat long data ; 0 for no data) from Strava GPS file , with run time for each GPS session in minutes (run time printed either on the plot or in a separate summary file);
> 
> What I mean by the word “session" is to remove the large dead time blocks between data collection- so if the unit was turned on on day 1 for 5.2 hrs and then turned off for five days and theen turned on again 5 days later and run for 24.3 hrs.  Then there would be 5.2 hrs identified for the first session and 24.3 hrs identified for the second session (instead of showing 149.5 hrs = 24.3 + 5*24 hrs + 5.2 hrs)
> 
> 
> Steven Chillrud
> 
> Lamont-Doherty Earth Observatory of Columbia Univ.
> 61 Rt 9W
> Palisades, NY 10964
> chilli@ldeo.columbia.edu <mailto:chilli@ldeo.columbia.edu>
> tel: 845-365-8893
> fax: 845-365-8155

Steven Chillrud

Lamont-Doherty Earth Observatory of Columbia Univ.
61 Rt 9W
Palisades, NY 10964
chilli@ldeo.columbia.edu
tel: 845-365-8893
fax: 845-365-8155

**Comment by caraMsmith** [comment]
@zross The times series of minute ventilation we want is the column titled "minute_ventilation_adjusted [ml/min]"

**Comment by zross** [comment]
I did see that note from Steve, in the comment above about what to plot I edited it based on Steve's note, but it's useful to have here also.

**Comment by zross** [comment]
@caraMsmith so no plots for pdr or abp right?
