### ISSUE TITLE
Convert and upload hexoskin binary files

### ISSUE THREAD

**Issue by zross** [zross/sensorDataImport#46]
We would like to upload the whole binary data folder to the database. Once uploaded, the following steps need to be completed:
1)    Convert the wav files to csv files.
a.     Hexoskin provides information on how this can be done. Hexoskin provides a program that can convert the files and also provides the source code and MatLab scripts if that is easier on your end. http://support.hexoskin.com/customer/portal/articles/1758581-how-do-i-convert-binary-data-downloaded-from-the-dashboard-
b.     The conversion program (i) converts the wav files to csv file and (ii) adds the unix time stamps to each file.
2)    Combine the individual files into one file based on the timestamp (each second). We want the resulting file to include the following variables (all of which appear in the original data files):
a.      Acceleration_X    (Ave 256 Hz data to 1 Hz)
b.    Acceleration_Y  (Ave 256 Hz data to 1 Hz)
c.     Acceleration_Z  (Ave 256 Hz data to 1 Hz)
d.    Activity (1 Hz)  Just for everyone’s information of what is already done by hexoskin the hexoskin server filtered the X,Y, Z data to remove the impact of gravity on each axis and then taken the square root of the sum of the squares and then averaged 256 Hz data to 1 second);. https://api.hexoskin.com/docs/resource/activity/ )
e.     Breathing_rate_bpm (1 Hz)
f.      Cadence_spm  (1 Hz)
g.     Heart_rate_bpm  (1 Hz)
h.     Minute_ventilation_adjusted_LPM (1 Hz)
i.      Minute_ventilation_raw_LPM  (1 Hz)
j.      Tidal_volume_adjusted_L  (1 Hz)
k.     Tidal_volume_raw_L  (1 Hz)
l.      TimeStamp

 
The 3 acceleration files (a,b, and c) will have an added step as they need to be averaged to seconds first. All other files should have a time base of 1 second.
Example files are here:
https://drive.google.com/file/d/0ByhwI_N5pW8dS2lTVlNibzNZRzg/view?usp=sharing 
https://drive.google.com/file/d/0ByhwI_N5pW8dZkxNSE4ydDY1ZHM/view?usp=sharing 

 (Hexoskin server provides both files to describe a single monitoring episode)

**Comment by zross** [comment]
@caraMsmith when you download, do you download as a ZIP? Should I let the user select a zip file, then unzip, convert to CSV etc or should I let them select a folder?

**Comment by caraMsmith** [comment]
@zross When I download the data from the hexoskin server, I have to download two items. The first is a .csv file that contains the timestamp, HR, RR, activity. The second, is the folder of binary data files. This _is_ a ZIP file, but my mac automatically unzips it in my downloads folder. This folder contains individual .wav files for different variables, but each files , annoyingly, does not contain the timestamp. Once I convert them to .csv files, I then add them to the .csv file I downloaded directly from the hexoskin sever. The handling of the hexoskin data is a little confusing, mostly because it's not very logical or user friendly. Perhaps we should arrange a time to share screens over Skype so I can walk you though the process? Would only take < 15 minutes

**Comment by zross** [comment]
OK, 15 minutes tomorrow sometime?

**Comment by caraMsmith** [comment]
Yea, anytime before 3:30 tomorrow works for me.

**Comment by zross** [comment]
There are some small differences in the names of files created by the command line tool and what you have above. Assume this is fine like:

* `Breathing_rate_bpm`: this does not exist, just `breathing_rate.csv` and `breathing_rate_quality.csv`
* Same for `Heart_rate_bpm`
* `Cadence_spm`: there is a `cadence.csv`

So I assume if you have a `bpm` or `spm` etc using the CSV that is closest in name is fine?

**Comment by caraMsmith** [comment]
yes, that is fine. And we just want the rate files, not the quality files

**Comment by caraMsmith** [comment]
Here is the updated list of files to be added (note: added the "device_position" file):
a.      Acceleration_X    (Ave 256 Hz data to 1 Hz)
b.    Acceleration_Y  (Ave 256 Hz data to 1 Hz)
c.     Acceleration_Z  (Ave 256 Hz data to 1 Hz)
d.    Activity (1 Hz)
e.     Breathing_rate (1 Hz)
f.      Cadence  (1 Hz)
g.   device_position
h.     Heart_rate  (1 Hz)
i.     Minute_ventilation_adjusted (1 Hz)
j.      Minute_ventilation_raw  (1 Hz)
k.      Tidal_volume_adjusted  (1 Hz)
l.     Tidal_volume_raw  (1 Hz)

**Comment by caraMsmith** [comment]
The device position file is a little strange too. Basically since the position doesn't change that much so they only record the times points when it changes. For example, at time 1 it lists the position as 2 and then the next line is time 30 and lists the position as 6. So time 2-29 is all position 2.

**Comment by zross** [comment]
OK, when you have a chance give me a zip file AND the Excel file you create from it so I can compare

**Comment by zross** [comment]
How do you want me to handle a slight difference between 256 Hz files and 1 Hz:

The 256 Hz files will range between 0.00 to 34546.36 etc while the 1Hz files range between 1 and 34546 (see below). I was initially rounding down but this gives 0-34546. Rounding up will give 1-34547 and rounding will give 0-34546. We want values to match the 1 Hz so 1-34546

My guess is that this is not a big deal at all but wanted your input. I propose the following:

Round all values and drop the 0 value **or** round all values and then round 0 and 1.

![image](https://cloud.githubusercontent.com/assets/1395177/24762528/acb1c490-1abc-11e7-931e-52837fd5b8ba.png)

**Comment by caraMsmith** [comment]
Yea, this isn't a big deal as either won't make a big difference. But lets do your second suggestion of rounding 0 to 1 so it matches the 1 hz range of 1 - 34546.

**Comment by zross** [comment]
This next issue also does not likely matter but:

My start date/time is `"2017-01-10 09:22:00 EST"`. If you look at the activity file CSV as an example, I'm seeing the 0.7382812 associated with second 4. So should this 09:22:04? This is what I have. Your method puts that at 09:22:05. I can stick with what I have or I can move everything by one second to match yours.

**Comment by caraMsmith** [comment]
The original csv from hexoskin has NA for each field for the first timepoint, which is causing the difference. You can stick with what you have.

**Comment by zross** [comment]
OK, here is my file you can compare. Let me know what you think. This is a CSV, but GitHub requires a `txt` extension.

[compare108680.txt](https://github.com/zross/sensorDataImport/files/903512/compare108680.txt)
