### ISSUE TITLE
Need to develop approach for adding "session" to database

### ISSUE THREAD

**Issue by zross** [zross/sensorDataImport#6]
For the GPS file we have just one file per session so no problem. Similarly for HXI we will have two per session so this is also easy. The MicroPEM, MicroAeth and ABP files all have just one file per study so we're coding them initially as S99 in the file name. How should we distinguish between sessions?

The database right now uses the session info from the file name for the biking data (S99) but this is mostly just a placeholder for the MicroPEM, MicroAeth and ABP.

**Comment by dwjack** [comment]
We also would like to make one minor change to the file naming convention:  it would be convenient to have the session id (which we had structured as S##) be S#-# where the first # is the session (1-5) and the second # is the order of the file associated with that session (1-9).    E.g., we might write S2-2 for the second file generated during the second session, or we might write S1-2 for the second file generated during the first session.

**Comment by zross** [comment]
Actually microaeth creates a different file each time.

**Comment by zross** [comment]
We discussed this and decided that the processing/upload step will do this by reviewing the dates and finding gaps that are 12 hours or longer then assigning session to the data. So if there are two gaps, then the first block of time gets session 01, then 02 then 03. Note that formatting that this is a string and not integer.

**Comment by zross** [comment]
Just FYI: In looking at micropem (BIKE0001_MPM01_S01_150626.csv), I'm seeing 5 gaps where time1-time2 < 43200 secs (12 hours).

**Comment by zross** [comment]
@dwjack is the pre pilot ABP data I have a "real" dataset? It is very short in terms of number of records (109). This is fine, the app handles the one-session file fine but I'm not able to see how it performs with a proper file.

**Comment by zross** [comment]
I've completed this -- we still need to decide about what should NOT be considered a session ( #27 )
